height: 500
menubar: true
toolbar:
  - undo redo | blocks | bold italic | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat | help | images_upload_url 
plugins:
  - insertdatetime lists media table code help wordcount
